Hotfix/1.0.2
aakbcms/ding_pretix pull request #2
Opened 2018-06-14 08:26 UTC by turegjorup

2018-06-14 09:38 UTC, cableman requested changes

2018-06-14 09:38 UTC, cableman commented on ding_pretix.module
> +  // If we are cloning we need to find and set the pretix settings from the event being cloned from
All comments should be a sentence with full stop.

2018-06-14 09:38 UTC, cableman commented on ding_pretix.module
> +    if($pretix_node_info['pretix_slug']) {
Missing space "if()".

2018-06-14 09:38 UTC, cableman commented on ding_pretix.module
> +    $node_settings = $node->clone_from_original_nid ? _ding_pretix_get_pretix_node_info($node->clone_from_original_nid) : null;
null should be NULL

2018-06-14 09:38 UTC, cableman commented on ding_pretix.module
> +    if($node_settings['maintain_copy']) {
Missing space "if(".

2018-06-14 09:38 UTC, cableman commented on includes/ding_pretix.api_module.inc
> + * @param $service_settings
Missing parameter documentation.

2018-06-14 09:38 UTC, cableman commented on includes/ding_pretix.api_module.inc
> + * @param $pretix_slug
Missing parameter documentation.

2018-06-14 09:38 UTC, cableman commented on includes/ding_pretix.api_module.inc
> + * @return mixed
Missing return documentation.

2018-06-14 09:38 UTC, cableman commented on includes/ding_pretix.api_module.inc
> +  $options = [
Could at static cache be used here?

2018-06-15 11:00 UTC, turegjorup commented
@cableman PR updated

2018-06-29 11:41 UTC, cableman requested changes

2018-06-29 11:41 UTC, cableman commented on ding_pretix.module
> + * @throws Exception if one of the INSERTs failed
The exception type should be defined if possible and comment on next line. See https://www.drupal.org/docs/develop/coding-standards/api-documentation-and-comment-standards#throws

2018-06-29 11:41 UTC, cableman commented on ding_pretix.module
> + * @throws Exception if one of the INSERTs failed
This is true for all @throws in the code

2018-06-29 11:41 UTC, cableman commented on ding_pretix.module
> + *   The node that is being deleted.
Hooks used short form comments normally: https://www.drupal.org/docs/develop/coding-standards/api-documentation-and-comment-standards#hookimpl

2018-06-29 11:41 UTC, cableman commented on ding_pretix.module
> + *   The node that is being deleted.
Please don't kill the messenger....

2018-06-29 11:41 UTC, cableman commented on ding_pretix.module
> +  // must be updated in pretix.
Comment should be an sentence stating with capital letter and end with .

2018-06-29 11:41 UTC, cableman commented on ding_pretix.module
> +  // must be updated in pretix.
Same here with comment

2018-06-29 11:41 UTC, cableman commented on includes/ding_pretix.api_module.inc
> + * @param bool $use_pdf_tickets
Documentation messing for $data and $use_pdf_tickets.

2018-06-29 11:41 UTC, cableman commented on includes/ding_pretix.api_module.inc
>   * @param $quota
Missing documentation for $quota.

2018-06-29 11:41 UTC, cableman commented on includes/ding_pretix.api_module.inc
>   * @throws Exception
Missing documentation?

2018-06-29 11:41 UTC, cableman commented on includes/ding_pretix.api_module.inc
>   * @throws Exception
Missing documentation?

2018-06-29 12:54 UTC, cableman approved these changes

2018-08-09 11:48 UTC, merged